git:
  autoFetch: false
  commit:
    signOff: false
  log:
    order: topo-order
    showGraph: "always"
    showWholeGraph: false
  paging:
    # cargo install git-delta
    colorArg: always
    useConfig: false
    pager: delta --paging=never
  parseEmoji: true
  skipHookPrefix: WIP
gui:
  authorColors:
    guanghechen: "#61AFEF"
  branchColors:
    main: "#FCA2AA" # orange
  border: "rounded"
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  mouseEvents: true
  nerdFontsVersion: "3"
  showBottomLine: true
  showCommandLog: true
  showFileTree: true
  showIcons: true
  showRandomTip: true
  splitDiff: auto
  theme:
    activeBorderColor:
      - bold
      - "#DE8C92" # baby_pink
    inactiveBorderColor:
      - default
      - "#ABB2BF" # white
    searchingActiveBorderColor:
      - default
      - "#FCA2AA" # orange
    optionsTextColor:
      - default
      - "#DE8C92" # baby_pink
    selectedLineBgColor:
      - default
      - "#6F737B" # light_grey
    cherryPickedCommitFgColor:
      - default
      - "#61AFEF" # blue
    cherryPickedCommitBgColor:
      - default
      - "#A3B8EF" # cyan
    markedBaseCommitFgColor:
      - default
      - "#7ECA9C" # vibrant_green
    markedBaseCommitBgColor:
      - default
      - "#81A1C1" # nord_blue
    unstagedChangesColor:
      - default
      - "#E06C75" # red
    defaultFgColor:
      - default
      - "#ABB2BF" # white
notARepository: skip
os:
  edit: "nvim"
  editAtLine: "nvim --line={{line}} {{filename}}"
  editAtLineAndWait: "nvim --block --line={{line}} {{filename}}"
  editInTerminal: true
  editPreset: "nvim-remote"
  openDirInEditor: "nvim {{dir}}"
promptToReturnFromSubprocess: true
